### ISSUE TITLE
Infinite loop in CSS self-referencing import

### ISSUE THREAD

**Issue by redwire** [equalitie/bundler#22]
Figured out by @scottstamp

Proof of concept:

`index.html`
```html
<!DOCTYPE html>
<html>
<head>
    <title>Hi</title>
    <link rel="stylesheet" href="main.css" />
</head>
<body>
    <p> Hello world! </p>
</body>
</html>
```
`main.css`
```css
@import url("secondary.css");

body {
    background-color: red;
    width: 100%;
    height: 100%;
}
```

`secondary.css`
```css
@import url("main.css");

h1 {
    color: red;
}
```
----------------

Node.js code

`index.js`
```js
"use strict";


let b = require('equalitie-bundler');

let bundler = new b.Bundler('http://localhost:8000/index.html');

console.log(b);
bundler.on('originalReceived', b.replaceCSSFiles);
bundler.on('resourceReceived', b.bundleCSSRecursively);

bundler.bundle((err, content) => {
    if (err) {
        console.log(err.message);
    } else {
        console.log(content);
    }
});
```

-------------------

If you now run a simple Python server in the directory with these files, and try to run the bundler code, it will try to recursively bundle CSS forever.
